version: '3.8'

services:
  logistics-db:
    container_name: logistics_db
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: logistics_db
      POSTGRES_PASSWORD: logistics_db
      POSTGRES_DB: logistics
    volumes:
      - logistics_db:/var/lib/postgresql/data
      - ./postgres-init/logistics/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tiniping_network

  hub-db:
    container_name: hub_db
    image: postgres
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: hub_db
      POSTGRES_PASSWORD: hub_db
      POSTGRES_DB: hub
    volumes:
      - hub_db:/var/lib/postgresql/data
      - ./postgres-init/hubs/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tiniping_network


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"
    networks:
      - tiniping_network

volumes:
  logistics_db:
  hub_db:

networks:
  tiniping_network:
    driver: bridge