spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/logistics
    username: logistics_db
    password: logistics_db
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

ai:
  google:
    api-key: "AIzaSyDfmYmCOroxT6Q_AJl6WQrAmw-pR9ld5cA"